# Generated by Django 4.2.30 on 2026-06-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_limite_pago', models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago')),
                ('archivo', models.FileField(blank=True, help_text='PDF o imagen de la OC del proveedor', upload_to='ocs/', verbose_name='Archivo OC')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Alerta al llegar a este nivel', verbose_name='Stock mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('referencia', models.CharField(blank=True, help_text='OC, orden de servicio, etc.', max_length=200, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
