# Generated by Django 4.2.30 on 2026-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('resumen', models.TextField(max_length=400, verbose_name='Resumen')),
                ('contenido', models.TextField(verbose_name='Contenido (HTML)')),
                ('imagen', models.URLField(blank=True, verbose_name='URL imagen')),
                ('autor', models.CharField(default='CACD Soluciones', max_length=100, verbose_name='Autor')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('icono', models.CharField(default='settings', max_length=50, verbose_name='Ícono (Material Symbol)')),
                ('color_gradiente', models.CharField(default='linear-gradient(135deg, #0066ff, #00ccff)', max_length=200, verbose_name='Gradiente CSS')),
                ('imagen', models.URLField(blank=True, verbose_name='URL imagen')),
                ('descripcion_corta', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('contenido', models.TextField(blank=True, help_text='Markdown o HTML con la descripción completa del servicio', verbose_name='Contenido detallado')),
                ('beneficios', models.TextField(blank=True, help_text='Un beneficio por línea', verbose_name='Beneficios')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
