# Generated by Django 4.2.30 on 2026-06-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pc', 'PC'), ('notebook', 'Notebook'), ('servidor', 'Servidor'), ('impresora', 'Impresora'), ('red', 'Equipo de Red'), ('ups', 'UPS'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='N° Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, verbose_name='N° Inventario')),
                ('especificaciones', models.TextField(blank=True, help_text='RAM, disco, CPU, SO, etc.', verbose_name='Especificaciones')),
                ('garantia_fin', models.DateField(blank=True, null=True, verbose_name='Garantía hasta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
