# Generated by Django 4.2.30 on 2026-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='disco_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial del disco'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='hostname',
            field=models.CharField(blank=True, help_text='Computer name detectado por script', max_length=100, verbose_name='Nombre PC'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Dirección MAC'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='motherboard_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial motherboard'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='uuid_bios',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UUID BIOS'),
        ),
    ]
