# Generated by Django 4.2.30 on 2026-06-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_user'),
        ('equipos', '0002_equipo_disco_serial_equipo_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
