# Generated by Django 4.2.30 on 2026-07-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientostock_producto'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='CACD Soluciones', max_length=200, verbose_name='Nombre empresa')),
                ('rut', models.CharField(default='', max_length=20, verbose_name='RUT')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ultimo_numero_cotizacion', models.IntegerField(default=0, verbose_name='Último N° cotización')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-numero'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CotizacionConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='cotizaciones.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Consulta de cliente',
                'verbose_name_plural': 'Consultas de clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
