# Generated by Django 4.2.30 on 2026-07-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_configuracion_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email_recepcion_dte',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email recepción DTE'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='giro',
            field=models.CharField(blank=True, default='Servicios de Informática', max_length=200, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='terminos_legales',
            field=models.TextField(blank=True, help_text='Texto completo de términos y condiciones para imprimir en cotizaciones', verbose_name='Términos legales'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=200, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye',
            field=models.TextField(blank=True, help_text='Texto de provisiones, instalación, etc.', verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(default='PESOS CHILE', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto descuento'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento global'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='unidad_negocio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unidad de negocio'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='porcentaje_descuento_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento item'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='recurso',
            field=models.CharField(blank=True, help_text='Código del recurso ej. 001AAA0055', max_length=50, verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='total_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total item'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='unidad',
            field=models.CharField(blank=True, help_text='ej. MES, UNIDAD, HORA', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario'),
        ),
    ]
