# Generated by Django 4.2.30 on 2026-07-15 02:39

from django.db import migrations


TERMINOS = """\
TÉRMINOS Y CONDICIONES

1. VALIDEZ DE LA OFERTA: Esta cotización tiene una validez de 15 días corridos desde su fecha de emisión.

2. IMPUESTOS: Todos los valores expresados en este documento son NETOS y no incluyen el 19% de IVA. El IVA será adicionado en la facturación correspondiente.

3. CONDICIONES DE PAGO:
   - Servicios de Proyecto: El pago deberá realizarse en un plazo máximo de siete (7) días corridos desde la emisión de la factura.
   - Servicios Recurrentes: La facturación se realizará por mes anticipado. El valor mensual será reajustado anualmente conforme a la variación acumulada del IPC.

4. MOROSIDAD: El atraso en el pago de las facturas devengará el interés máximo convencional permitido por la ley, calculado desde el día siguiente al vencimiento hasta la fecha del pago efectivo. En caso de mora superior a 15 días corridos, CACD Soluciones se reserva el derecho de suspender temporalmente el servicio de soporte o el acceso a la infraestructura hasta la regularización de la deuda.

5. DELIMITACIÓN DEL ALCANCE: Cualquier requerimiento, desarrollo, configuración, equipamiento o visita técnica no descrita explícitamente en la cláusula de Descripción y Alcance de esta cotización, se considerará un servicio adicional y será cotizado por separado.

6. RESPONSABILIDADES DEL CLIENTE: El cliente deberá proveer los accesos necesarios (credenciales, servidores, energía eléctrica) en las fechas acordadas. Los retrasos atribuibles al cliente extenderán proporcionalmente los plazos de entrega del proyecto.

7. GARANTÍA TÉCNICA (SLA): Se otorga una garantía técnica de 30 días corridos tras la entrega y/o puesta en marcha del proyecto, exclusiva para la corrección de errores atribuibles a la instalación o desarrollo. Esta garantía quedará anulada automáticamente si el cliente o un tercero ajeno a CACD Soluciones manipula, interviene o modifica el código fuente, la configuración de los equipos o la topología de la red entregada. Las garantías del hardware instalado se rigen exclusivamente por las políticas de sus respectivos fabricantes.

8. CONFIDENCIALIDAD Y MANEJO DE DATOS: Toda información, credenciales y bases de datos a las que CACD Soluciones tenga acceso serán tratadas con estricta confidencialidad, en conformidad con la Ley N° 19.628 sobre Protección de la Vida Privada.

9. PROPIEDAD INTELECTUAL: La propiedad intelectual de los desarrollos, scripts o configuraciones creadas pertenece a CACD Soluciones, y solo se transferirá el derecho de uso (licencia) al cliente una vez verificado el pago del 100% del proyecto correspondiente.

10. ACEPTACIÓN DE LA PROPUESTA: El inicio de los servicios prestados por CACD Soluciones está sujeto a la aceptación de los términos detallados en este documento. Para dar curso formal a esta cotización, se deberá responder este correo confirmando su aprobación o emitiendo la Orden de Compra respectiva haciendo referencia al número de esta cotización.
"""


def seed_terminos(apps, schema_editor):
    Configuracion = apps.get_model('cotizaciones', 'Configuracion')
    config, _ = Configuracion.objects.get_or_create(pk=1)
    if not config.terminos_legales:
        config.terminos_legales = TERMINOS
        config.giro = 'Servicios de Informática'
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_configuracion_email_recepcion_dte_configuracion_giro_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_terminos, migrations.RunPython.noop),
    ]
