# Generated by Django 4.2.30 on 2026-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_seed_terminos_legales'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='costo_hora',
            field=models.DecimalField(decimal_places=0, default=40845, help_text='Costo por hora de servicio para cálculo de margen', max_digits=12, verbose_name='Costo por hora (CLP)'),
        ),
    ]
