# Generated by Django 4.2.30 on 2026-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='N° Serie')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('tecnico_asignado', models.CharField(blank=True, max_length=100, verbose_name='Técnico asignado')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('reparacion', 'En Reparación'), ('baja', 'Dado de Baja')], default='operativo', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['nombre'],
            },
        ),
    ]
