# Generated by Django 4.2.30 on 2026-06-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('clientes', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(blank=True, max_length=100, verbose_name='Técnico')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio trabajo')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha término trabajo')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico / Hallazgos')),
                ('trabajo_realizado', models.TextField(blank=True, verbose_name='Trabajo realizado')),
                ('software_instalado', models.TextField(blank=True, help_text='Listar programas instalados o removidos', verbose_name='Software instalado/desinstalado')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas trabajadas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('facturado', 'Facturado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('garantia_fin', models.DateField(blank=True, null=True, verbose_name='Garantía hasta')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clientes.cliente', verbose_name='Cliente')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='ordenes.ordenservicio', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Repuesto usado',
                'verbose_name_plural': 'Repuestos usados',
            },
        ),
        migrations.CreateModel(
            name='FotoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes_fotos/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subida')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.ordenservicio', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
