# Generated by Django 4.2.30 on 2026-06-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Código de seguimiento'),
        ),
    ]
