# Generated by Django 4.2.30 on 2026-06-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientostock_producto'),
        ('ordenes', '0002_ordenservicio_codigo_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuestousado',
            options={'verbose_name': 'Ítem de cobro', 'verbose_name_plural': 'Detalle del cobro'},
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='motivo',
            field=models.TextField(blank=True, help_text='Lo que reporta el cliente', verbose_name='Motivo del servicio'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='orden_compra_archivo',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_oc/', verbose_name='Documento OC'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='orden_compra_cliente',
            field=models.CharField(blank=True, help_text='N° de OC del cliente', max_length=100, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='repuestousado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Sin IVA', max_digits=10, verbose_name='Valor unitario neto'),
        ),
        migrations.AlterField(
            model_name='repuestousado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto/Servicio'),
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('es_tecnico', models.BooleanField(default=False, verbose_name='Es del técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ordenes.ordenservicio', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
    ]
