# Generated by Django 4.2.30 on 2026-06-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientostock_producto'),
        ('ordenes', '0002_ordenservicio_codigo_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuestousado',
            options={'verbose_name': 'Ítem de cobro', 'verbose_name_plural': 'Detalle del cobro'},
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre contacto'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email contacto'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='motivo',
            field=models.TextField(blank=True, help_text='Lo que reporta el cliente', verbose_name='Motivo del servicio'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='orden_compra_archivo',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_oc/', verbose_name='Documento OC'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='orden_compra_cliente',
            field=models.CharField(blank=True, help_text='N° de OC del cliente', max_length=100, verbose_name='Orden de compra'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono contacto'),
        ),
        migrations.AlterField(
            model_name='repuestousado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Sin IVA', max_digits=10, verbose_name='Valor unitario neto'),
        ),
        migrations.AlterField(
            model_name='repuestousado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto/Servicio'),
        ),
    ]
