# Generated by Django 4.2.30 on 2026-06-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_repuestousado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('es_tecnico', models.BooleanField(default=False, verbose_name='Es del técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ordenes.ordenservicio', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
    ]
