# Generated by Django 4.2.30 on 2026-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_repuestousado_options_ordenservicio_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre contacto'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email contacto'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono contacto'),
        ),
    ]
