# Generated by Django 4.2.30 on 2026-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_comentarioticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='oc_aprobada',
            field=models.BooleanField(default=False, verbose_name='OC aprobada'),
        ),
    ]
