# Generated by Django 4.2.30 on 2026-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_ordenservicio_oc_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='archivo_identificacion',
            field=models.FileField(blank=True, help_text='.txt generado por el script que el cliente sube', null=True, upload_to='identificacion/', verbose_name='Informe del cliente'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='datos_identificacion',
            field=models.TextField(blank=True, help_text='JSON con hardware, software y errores detectados por script', verbose_name='Datos identificación PC'),
        ),
    ]
