# Generated by Django 4.2.30 on 2026-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_ordenservicio_archivo_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='horas_cobradas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas cobradas al cliente por este servicio', max_digits=8, null=True, verbose_name='Horas cobradas'),
        ),
    ]
