# Generated by Django 4.2.30 on 2026-07-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0007_auto_20260712_2052"),
        ("ordenes", "0007_ordenservicio_horas_cobradas"),
    ]

    operations = []
